# Generated by Django 4.1 on 2023-07-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blogs'),
        ),
    ]
