# Generated by Django 4.1 on 2023-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blogposts_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
