# Generated by Django 4.1 on 2023-07-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='groups'),
        ),
    ]
