# Generated by Django 4.1 on 2023-07-09 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
